### ISSUE TITLE
Upgrade script not successfully migrating database

### ISSUE THREAD

**Issue by naconner** [lamassu/lamassu-install#12]
After running the upgrade script, errors such as these have been frequently observed:

```
[2015-04-29T18:42:42.129Z]  WARN: lamassu-server/856 on lamassu-102: relation "pending_transactions" does not exist (err.code=42P01)
    error: relation "pending_transactions" does not exist
        at Connection.parseE (/usr/local/lib/node_modules/lamassu-server/node_modules/pg/lib/connection.js:561:11)
        at Connection.parseMessage (/usr/local/lib/node_modules/lamassu-server/node_modules/pg/lib/connection.js:390:17)
        at null.<anonymous> (/usr/local/lib/node_modules/lamassu-server/node_modules/pg/lib/connection.js:92:20)
        at Socket.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:764:14)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:426:10)
        at emitReadable (_stream_readable.js:422:5)
        at readableAddChunk (_stream_readable.js:165:9)
        at Socket.Readable.push (_stream_readable.js:127:10)
DELETE FROM pending_transactions WHERE incoming AND extract(EPOCH FROM now() - updated) > $1
[ '130' ]
[2015-04-29T18:42:44.130Z] ERROR: lamassu-server/856 on lamassu-102: relation "pending_transactions" does not exist (err.code=42P01)
    error: relation "pending_transactions" does not exist
        at Connection.parseE (/usr/local/lib/node_modules/lamassu-server/node_modules/pg/lib/connection.js:561:11)
        at Connection.parseMessage (/usr/local/lib/node_modules/lamassu-server/node_modules/pg/lib/connection.js:390:17)
        at null.<anonymous> (/usr/local/lib/node_modules/lamassu-server/node_modules/pg/lib/connection.js:92:20)
        at Socket.emit (events.js:95:17)
        at Socket.<anonymous> (_stream_readable.js:764:14)
        at Socket.emit (events.js:92:17)
        at emitReadable_ (_stream_readable.js:426:10)
        at emitReadable (_stream_readable.js:422:5)
        at readableAddChunk (_stream_readable.js:165:9)
        at Socket.Readable.push (_stream_readable.js:127:10)
SELECT * FROM pending_transactions WHERE (incoming OR extract(EPOCH FROM now() - updated) > $1) ORDER BY updated ASC
[ '70' ]
```

They've been resolved so far by running the migrate script manually:

```
cd /usr/local/lib/node_modules/lamassu-server

curl -#o /usr/local/bin/migrate https://gist.githubusercontent.com/naconner/3086b79a89f07ec71a57/raw/7863009ad9058f26eb17a77d29b72301245ea343/migrate && chmod 755 /usr/local/bin/migrate && node /usr/local/bin/migrate
```

So far, I've been unable to replicate this in-house.

**Comment by naconner** [comment]
This is the lamassu-upgrade.log from such an instance, although retrieved after manually running migrate:

https://gist.github.com/richardsj/02f8d86ba41be41f0ba9

**Comment by joshmh** [comment]
Old version, closing.
